fos_rest:
    #param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
#        rules:
#            - {path: '^/api/', priorities: ['json', 'xml'], fallback_format: json}
        #routing_loader: true
        #default_format: json
        #include_format: false
    view:
        view_response_listener: 'force'
        formats:
            json: true
