nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: [ ]
        allow_headers: [ ]
        allow_methods: [ ]
        expose_headers: [ ]
        max_age: 0
        hosts: [ ]
        origin_regex: false
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
            allow_headers: [ 'Content-Type', 'Accept-Encoding', 'Cache-Control', 'X-Requested-With', 'DNT', 'X-Bounce-Params', 'Authorization' ,'Access-Control-Allow-Private-Network']
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'PATCH' ]
            expose_headers: [ 'X-Total-Count', 'X-Page-Number', 'Location', 'Link', 'Content-Disposition', 'X-Bounce-Params', 'Access-Control-Allow-Private-Network']
            max_age: 3600