security:

    password_hashers:
        App\Entity\Users: 'auto'
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost:      15

    role_hierarchy:
        ROLE_ADMIN: [ 'ROLE_USER' ]
        ROLE_USER: [ ]

    providers:
#        app_user_provider:
#            entity:
#                class: App\Entity\Users
#                property: email
        app_users:
            entity: { class: App\Entity\Users, property: email }

        in_memory:
            memory:
                users:
                    api_user: { password: sGbIrB63C6r+0uADXrlePaE/3DUnD9gekpP9vCTMPMaMSBjdiOd3pIREA5v4DGVfWuh/cpX4XbbHLEw5grbVpQ== }

    enable_authenticator_manager: true

    firewalls:
        api:
            pattern:   ^\/api\/v[0-9]\/.*
            stateless: true
            jwt: ~
            provider: app_users

        secured_area:
            pattern: ^\/api\/doc
            http_basic:
                realm: 'API Documentation'
                provider: in_memory

    access_control:
        - { path: ^\/api\/v[ 0-9 ]\/.*, roles: PUBLIC_ACCESS }
        - { path: ^\/api\/v[ 0-9 ]\/secured\/.*, roles: IS_AUTHENTICATED_FULLY }
