parameters:
    slack_token: '%env(SLACK_TOKEN)%'
    slack_bot_name: '@@%env(APP_ENV)% %env(API_NAME)%'
    env: 'prod'

monolog:
    handlers:

        slack_debug:
            type: slack
            token: '%slack_token%'
            channel: '%env%_info'
            bot_name: '%slack_bot_name%'
            icon_emoji: ':speech_balloon:'
            level: info
            include_extra: true

        slack_error:
            type: slack
            token: '%slack_token%'
            channel: '%env%_error'
            bot_name: '%slack_bot_name%'
            icon_emoji: ':exclamation:'
            level: error
            include_extra: true

        symfony_mailer:
            type: symfony_mailer
            from_email: '%env(EMAIL_NOTIFICATION_FROM_EMAIL)%'
            to_email: [ '%env(MAINTAINER_EMAIL)%' ]
            subject: 'An Error Occurred on %env(APP_ENV)%! %%message%%'
            level: error
            formatter: monolog.formatter.html
            content_type: text/html
