#api_authentication:
#    path: /api/v1/auth
#    methods: ["POST"]
#
#gesdinet_jwt_refresh_token:
#    path: /api/v1/token/refresh

not_found_catchall_en:
    path: /{whatever}
    controller: App\Controller\ApiController::pageNotFoundAction
    requirements:
        whatever: .+

not_found_catchall:
    path: /
    controller: App\Controller\ApiController::pageNotFoundAction
    requirements:
        whatever: .+
